version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      minor-development-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      minor-production-deps:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      - dependency-name: '@apidevtools/json-schema-ref-parser'
        versions:
          # `@apidevtools/json-schema-ref-parser` went ESM only with v15 and it'll be a little bit
          # of work to upgrade us. Temporarily ignoring until we have the capacity to handle this.
          - '>= 15'
