root: true
extends: "@readme/eslint-config"
env:
  browser: true
  node: true
  mocha: true
rules:
  no-plusplus: off
  no-restricted-syntax: off
  no-underscore-dangle: off
  no-use-before-define: off
  prefer-rest-params: off
  prefer-spread: off
