#!/usr/bin/env node
const path = require('path');
const fs = require('fs');

(async () => {
  const out = {};
  const files = await fs.readdirSync(path.join(__dirname, './src'));

  files
    .filter(har => {
      return har.indexOf('.har') !== -1;
    })
    .forEach(har => {
      out[har.replace('.har', '')] = JSON.parse(fs.readFileSync(path.join(__dirname, `./src/${har}`), 'utf8'));
    });

  const build = `// This file is autogenerated. Run \`npm run build\` to update it.

module.exports = ${JSON.stringify(out, undefined, 2)};`;

  fs.writeFileSync('index.js', build);
})();
