module.exports = {
  'application-form-encoded': require('./src/application-form-encoded.har'),
  'application-json': require('./src/application-json.har'),
  cookies: require('./src/cookies.har'),
  full: require('./src/full.har'),
  headers: require('./src/headers.har'),
  https: require('./src/https.har'),
  'jsonObj-multiline': require('./src/jsonObj-multiline.har'),
  'jsonObj-null-value': require('./src/jsonObj-null-value.har'),
  'multipart-data-dataurl': require('./src/multipart-data-dataurl.har'),
  'multipart-data': require('./src/multipart-data.har'),
  'multipart-file': require('./src/multipart-file.har'),
  'multipart-form-data': require('./src/multipart-form-data.har'),
  query: require('./src/query.har'),
  short: require('./src/short.har'),
  'text-plain': require('./src/text-plain.har'),
  xml: require('./src/xml.har'),
}
